In [ ]:
#Instalar MolVS
!pip install -q molvs

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for molvs (setup.py) ... done

In [ ]:
# Instalar rdkit
!pip -q install rdkit.pypi==2021.9.4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.8/20.8 MB 41.8 MB/s eta 0:00:00

In [ ]:
#Importar librerías necesarias
import pandas as pd
from rdkit import Chem
from rdkit.Chem import PandasTools
from rdkit.Chem import rdMolDescriptors
from molvs.standardize import Standardizer
from molvs.charge import Uncharger, Reionizer
from molvs.fragment import LargestFragmentChooser
from molvs.tautomer import TautomerCanonicalizer
from rdkit.Chem.rdmolops import GetFormalCharge, RemoveStereochemistry

In [ ]:
# Cargar los DataFrames desde archivos CSV
Leadlikeness_compounds = pd.read_csv('/content/drive/MyDrive/Doctorado/Set de Datos 2/Objetivo 4/6_Compuestos a probar/Leadlikeness_compounds.csv')
#FDA
url_fda = "https://raw.githubusercontent.com/DIFACQUIM/Cursos/main/Datasets/FDA_2022_july_05_curada.csv"
FDA = pd.read_csv(url_fda)

In [ ]:
FDA

,ID,SMILES,NEW_SMILES,Data set
0,DB00006,CC[C@H](C)[C@H](NC(=O)[C@H](CCC(O)=O)NC(=O)[C@...,CCC(C)C(NC(=O)C(CCC(=O)O)NC(=O)C(CCC(=O)O)NC(=...,FDA
1,DB00007,CCNC(=O)[C@@H]1CCCN1C(=O)[C@H](CCCNC(N)=N)NC(=...,CCNC(=O)C1CCCN1C(=O)C(CCCN=C(N)N)NC(=O)C(CC(C)...,FDA
2,DB00014,CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...,CC(C)CC(NC(=O)C(COC(C)(C)C)NC(=O)C(Cc1ccc(O)cc...,FDA
3,DB00027,CC(C)C[C@@H](NC(=O)CNC(=O)[C@@H](NC=O)C(C)C)C(...,CC(C)CC(NC(=O)CNC(=O)C(NC=O)C(C)C)C(=O)NC(C)C(...,FDA
4,DB00035,NC(=O)CC[C@@H]1NC(=O)[C@H](CC2=CC=CC=C2)NC(=O)...,N=C(N)NCCCC(NC(=O)C1CCCN1C(=O)C1CSSCCC(=O)NC(C...,FDA
...,...,...,...,...
2304,DB16627,CCOC(=O)[C@H](CC1=CC=C(F)C=C1)NC(=O)[C@@H](N)C...,CCOC(=O)C(Cc1ccc(F)cc1)NC(=O)C(N)Cc1ccc(N(CCCl...,FDA
2305,DB16628,[H][C@@]12COP(O)(=O)O[C@]1([H])C(O)(O)[C@]1([H...,N=c1[nH]c2c(c(=O)[nH]1)NC1C(N2)OC2CO[PH](=O)(=...,FDA
2306,DB16629,[H][C@@]1(CCCCN1C(=O)OC[N+]1=CC=CC(=C1)C(=O)N[...,COC(=O)C(c1ccccc1)C1CCCCN1C(=O)OC[n+]1cccc(C(=...,FDA
2307,DB16703,CC(C)NC(=O)COC1=CC=CC(=C1)C1=NC2=C(C=CC=C2)C(N...,CC(C)NC(=O)COc1cccc(-c2nc(=Nc3ccc4[nH]ncc4c3)c...,FDA
2308,DB16741,[H][C@@]1(OB(O[C@]1([H])[C@H](O)CO)[C@H](CC(C)...,CC(C)CC(NC(=O)C(Cc1ccccc1)NC(=O)c1cnccn1)B1OC(...,FDA

In [ ]:
Leadlikeness_compounds

,Name,SMILES,Total Molweight,cLogP,H-Acceptors,H-Donors,Total Surface Area,Relative PSA,Rotatable Bonds,Senotherapeutics:,Leadlikeness
0,"(5-(2,4-bis((3S)-3-methylmorpholin-4-yl)pyrido...",CC1COCCN1C2=NC(=NC3=C2C=CC(=N3)C4=CC(=C(C=C4)O...,465.552,2.4865,9,1,351.95,0.23614,5,1,True
1,(E)-4-((2-N-(4-methoxybenzenesulfonyl)amino)st...,COC1=CC=C(C=C1)S(=O)(=O)N=C2C=CC=CC2=CC=C3C=CN...,382.439,1.7590,6,1,292.14,0.22845,3,1,True
2,10-decarbamoylmitomycin C,CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2CO)OC)N4)N,291.306,-1.6656,7,3,197.58,0.45359,2,1,True
3,10-hydroxycamptothecin,CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=CC(=...,364.356,0.8381,7,2,246.20,0.31194,1,1,True
4,103D5R,CC(C1=C(C2=C(C=C1)OC(C=C2)(C)C)OC)N3C=NC4=C3C=...,335.406,4.0763,5,0,259.29,0.18824,3,1,True
...,...,...,...,...,...,...,...,...,...,...,...
265,vistusertib,CC1COCCN1C2=NC(=NC3=C2C=CC(=N3)C4=CC(=CC=C4)C(...,462.552,2.5926,9,1,351.05,0.24073,4,1,True
266,withaferin A,CC1=C(C(=O)OC(C1)C(C)C2CCC3C2(CCC4C3CC5C6(C4(C...,470.604,2.4938,6,2,334.36,0.23905,3,1,True
267,withanone,CC1=C(C(=O)OC(C1)C(C)C2(CCC3C2(CCC4C3C5C(O5)C6...,470.604,2.5971,6,2,330.77,0.24165,2,1,True
268,zomepirac glucuronide,CC1=C(N(C(=C1)CC(=O)OC2C(C(C(C(O2)C(=O)O)O)O)O...,467.857,-0.0007,10,4,323.57,0.36589,7,1,True
269,zopolrestat,C1=CC=C2C(=C1)C(=NN(C2=O)CC3=NC4=C(S3)C=CC(=C4...,419.382,2.9351,6,1,280.92,0.30461,5,1,True

In [ ]:
#Función para curado
def pretreatment(smi):
    try:
        mol = Chem.MolFromSmiles(smi)
        if mol == None:
            #If rdkit could not parse the smiles, returns Error 1
            return "Error 1"
        else:
            mol = STD(mol)
            mol = LFC(mol)

            allowed_elements = {"H","B","C","N","O","F","Si","P","S","Cl","Se","Br","I"}
            actual_elements = set([atom.GetSymbol() for atom in mol.GetAtoms()])
            if len(actual_elements-allowed_elements) == 0:
                mol = UC(mol)
                mol = RI(mol)
                #RemoveStereochemistry(mol)
                mol = TC(mol)
                return Chem.MolToSmiles(mol)
            else:
                # If molecule contains other than the allowed elements, return "Error 2"
                return "Error 2"
    except:
        return "Something else was found"

In [ ]:
#Definir funciones
STD = Standardizer() # Get the standardized version of a given SMILES string (canonical SMILES).
LFC = LargestFragmentChooser() # Select the largest fragment from a salt (ionic compound).
UC = Uncharger() # Charge corrections are applied to ensure, for example, that free metals are correctly ionized.
RI = Reionizer() # Neutralize molecule by adding/removing hydrogens.
TC = TautomerCanonicalizer()  # Return a tautormer “reasonable” from a chemist’s point, but isn’t guaranteed to be the most energetically favourable.

In [ ]:
#Nueva columna de SMILES
Leadlikeness_compounds["NEW_SMILES"] = [pretreatment(x) for x in Leadlikeness_compounds["SMILES"]]
Leadlikeness_compounds.head()

WARNING:molvs.tautomer:Tautomer enumeration stopped at maximum 1000
WARNING:molvs.tautomer:Tautomer enumeration stopped at maximum 1000
WARNING:molvs.tautomer:Tautomer enumeration stopped at maximum 1000

,Name,SMILES,Total Molweight,cLogP,H-Acceptors,H-Donors,Total Surface Area,Relative PSA,Rotatable Bonds,Senotherapeutics:,Leadlikeness,NEW_SMILES
0,"(5-(2,4-bis((3S)-3-methylmorpholin-4-yl)pyrido...",CC1COCCN1C2=NC(=NC3=C2C=CC(=N3)C4=CC(=C(C=C4)O...,465.552,2.4865,9,1,351.95,0.23614,5,1,True,COc1ccc(-c2ccc3c(N4CCOCC4C)nc(N4CCOCC4C)nc3n2)...
1,(E)-4-((2-N-(4-methoxybenzenesulfonyl)amino)st...,COC1=CC=C(C=C1)S(=O)(=O)N=C2C=CC=CC2=CC=C3C=CN...,382.439,1.7590,6,1,292.14,0.22845,3,1,True,COc1ccc(S(=O)(=O)N=C2C=CC=CC2=CC=C2C=CN(O)C=C2...
2,10-decarbamoylmitomycin C,CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2CO)OC)N4)N,291.306,-1.6656,7,3,197.58,0.45359,2,1,True,COC12C(C=O)c3c(O)c(N)c(C)c(O)c3N1CC1NC12
3,10-hydroxycamptothecin,CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=CC(=...,364.356,0.8381,7,2,246.20,0.31194,1,1,True,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cc(O)ccc3nc2-1
4,103D5R,CC(C1=C(C2=C(C=C1)OC(C=C2)(C)C)OC)N3C=NC4=C3C=...,335.406,4.0763,5,0,259.29,0.18824,3,1,True,COc1c(C(C)n2cnc3ncccc32)ccc2c1C=CC(C)(C)O2

In [ ]:
Leadlikeness_compounds

,Name,SMILES,Total Molweight,cLogP,H-Acceptors,H-Donors,Total Surface Area,Relative PSA,Rotatable Bonds,Senotherapeutics:,Leadlikeness,NEW_SMILES
0,"(5-(2,4-bis((3S)-3-methylmorpholin-4-yl)pyrido...",CC1COCCN1C2=NC(=NC3=C2C=CC(=N3)C4=CC(=C(C=C4)O...,465.552,2.4865,9,1,351.95,0.23614,5,1,True,COc1ccc(-c2ccc3c(N4CCOCC4C)nc(N4CCOCC4C)nc3n2)...
1,(E)-4-((2-N-(4-methoxybenzenesulfonyl)amino)st...,COC1=CC=C(C=C1)S(=O)(=O)N=C2C=CC=CC2=CC=C3C=CN...,382.439,1.7590,6,1,292.14,0.22845,3,1,True,COc1ccc(S(=O)(=O)N=C2C=CC=CC2=CC=C2C=CN(O)C=C2...
2,10-decarbamoylmitomycin C,CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2CO)OC)N4)N,291.306,-1.6656,7,3,197.58,0.45359,2,1,True,COC12C(C=O)c3c(O)c(N)c(C)c(O)c3N1CC1NC12
3,10-hydroxycamptothecin,CCC1(C2=C(COC1=O)C(=O)N3CC4=C(C3=C2)N=C5C=CC(=...,364.356,0.8381,7,2,246.20,0.31194,1,1,True,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cc(O)ccc3nc2-1
4,103D5R,CC(C1=C(C2=C(C=C1)OC(C=C2)(C)C)OC)N3C=NC4=C3C=...,335.406,4.0763,5,0,259.29,0.18824,3,1,True,COc1c(C(C)n2cnc3ncccc32)ccc2c1C=CC(C)(C)O2
...,...,...,...,...,...,...,...,...,...,...,...,...
265,vistusertib,CC1COCCN1C2=NC(=NC3=C2C=CC(=N3)C4=CC(=CC=C4)C(...,462.552,2.5926,9,1,351.05,0.24073,4,1,True,CNC(=O)c1cccc(-c2ccc3c(N4CCOCC4C)nc(N4CCOCC4C)...
266,withaferin A,CC1=C(C(=O)OC(C1)C(C)C2CCC3C2(CCC4C3CC5C6(C4(C...,470.604,2.4938,6,2,334.36,0.23905,3,1,True,CC1=C(CO)C(=O)OC(C(C)C2CCC3C4CC5OC56C(=O)CCC(=...
267,withanone,CC1=C(C(=O)OC(C1)C(C)C2(CCC3C2(CCC4C3C5C(O5)C6...,470.604,2.5971,6,2,330.77,0.24165,2,1,True,CC1=C(C)C(=O)OC(C(C)C2(O)CCC3C4C5OC5C5(O)C=CCC...
268,zomepirac glucuronide,CC1=C(N(C(=C1)CC(=O)OC2C(C(C(C(O2)C(=O)O)O)O)O...,467.857,-0.0007,10,4,323.57,0.36589,7,1,True,Cc1cc(CC(=O)OC2OC(C(=O)O)C(O)C(O)C2O)n(C)c1C(=...
269,zopolrestat,C1=CC=C2C(=C1)C(=NN(C2=O)CC3=NC4=C(S3)C=CC(=C4...,419.382,2.9351,6,1,280.92,0.30461,5,1,True,O=C(O)Cc1nn(Cc2nc3cc(C(F)(F)F)ccc3s2)c(=O)c2cc...

In [ ]:
# Filtrar CTD_DesMol_curado según los valores en la columna 'Name' de Leadlikeness_compounds
resultados = FDA[FDA['NEW_SMILES'].isin(Leadlikeness_compounds['NEW_SMILES'])]

In [ ]:
resultados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, 31 to 2167
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          49 non-null     object
 1   SMILES      49 non-null     object
 2   NEW_SMILES  49 non-null     object
 3   Data set    49 non-null     object
dtypes: object(4)
memory usage: 1.9+ KB

In [ ]:
# prompt: agragar el resto de columnas

# Agregar el resto de columnas de FDA a los resultados
resultados = pd.merge(resultados, Leadlikeness_compounds, on='NEW_SMILES', how='left')
resultados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  49 non-null     object
 1   SMILES_x            49 non-null     object
 2   NEW_SMILES          49 non-null     object
 3   Data set            49 non-null     object
 4   Name                49 non-null     object
 5   SMILES_y            49 non-null     object
 6   Total Molweight     49 non-null     float64
 7   cLogP               49 non-null     float64
 8   H-Acceptors         49 non-null     int64
 9   H-Donors            49 non-null     int64
 10  Total Surface Area  49 non-null     float64
 11  Relative PSA        49 non-null     float64
 12  Rotatable Bonds     49 non-null     int64
 13  Senotherapeutics:   49 non-null     int64
 14  Leadlikeness        49 non-null     bool
dtypes: bool(1), float64(4), int64(4), object(6)
memory usage: 5.5+ KB

In [ ]:
resultados

,ID,SMILES_x,NEW_SMILES,Data set,Name,SMILES_y,Total Molweight,cLogP,H-Acceptors,H-Donors,Total Surface Area,Relative PSA,Rotatable Bonds,Senotherapeutics:,Leadlikeness
0,DB00140,CC1=C(C)C=C2N(C[C@H](O)[C@H](O)[C@H](O)CO)C3=N...,Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(CC(O)C(O)C(O)CO)c...,FDA,Riboflavin,CC1=CC2=C(C=C1C)N(C3=NC(=O)NC(=O)C3=N2)CC(C(C(...,376.368,-2.0663,10,5,264.40,0.44066,5,1,True
1,DB00197,CC1=C(C)C2=C(CCC(C)(COC3=CC=C(CC4SC(=O)NC4=O)C...,Cc1c(C)c2c(c(C)c1O)CCC(C)(COc1ccc(Cc3sc(=O)[nH...,FDA,Troglitazone,CC1=C(C2=C(CCC(O2)(C)COC3=CC=C(C=C3)CC4C(=O)NC...,441.546,4.3852,6,2,323.81,0.27217,5,1,True
2,DB00222,CCC1=C(C)CN(C(=O)NCCC2=CC=C(C=C2)S(=O)(=O)NC(=...,CCc1c(C)cn(C(=O)NCCc2ccc(S(=O)(=O)NC(=O)NC3CCC...,FDA,glimepiride,CCC1=C(CN(C1=O)C(=O)NCCC2=CC=C(C=C2)S(=O)(=O)N...,490.623,3.5186,9,3,367.55,0.28739,6,1,True
3,DB00227,[H][C@]12[C@H](C[C@@H](C)C=C1C=C[C@H](C)[C@@H]...,CCC(C)C(=O)OC1CC(C)C=C2C=CC(C)C(CCC3CC(O)CC(=O...,FDA,Lovastatin,CCC(C)C(=O)OC1CC(C=C2C1C(C(C=C2)C)CCC3CC(CC(=O...,404.545,3.8950,5,1,317.66,0.18630,7,1,True
4,DB00266,OC1=C(CC2=C(O)C3=C(OC2=O)C=CC=C3)C(=O)OC2=C1C=...,O=c1c(Cc2c(O)oc3ccccc3c2=O)c(O)oc2ccccc12,FDA,Dicumarol,C1=CC=C2C(=C1)C(=C(C(=O)O2)CC3=C(C4=CC=CC=C4OC...,336.298,2.5880,6,2,233.82,0.30913,2,1,True
5,DB00275,CCCC1=NC(=C(N1CC1=CC=C(C=C1)C1=C(C=CC=C1)C1=NN...,CCCc1nc(C(C)(C)O)c(C(=O)O)n1Cc1ccc(-c2ccccc2-c...,FDA,olmesartan,CCCC1=NC(=C(N1CC2=CC=C(C=C2)C3=CC=CC=C3C4=NNN=...,446.509,3.2081,9,3,345.27,0.30116,8,1,True
6,DB00301,[H][C@]12SC(C)(C)[C@@H](N1C(=O)[C@H]2NC(=O)C1=...,Cc1onc(-c2c(F)cccc2Cl)c1C(=O)NC1C(=O)N2C1SC(C)...,FDA,Floxacillin,CC1=C(C(=NO1)C2=C(C=CC=C2Cl)F)C(=O)NC3C4N(C3=O...,453.877,2.8046,8,2,299.78,0.36627,4,1,True
7,DB00305,[H][C@]12CN3C4=C([C@@H](COC(N)=O)[C@@]3(OC)[C@...,COC12C(=COC(N)=O)c3c(O)c(N)c(C)c(O)c3N1CC1NC12,FDA,Mitomycin,CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)N)OC)N4)N,334.331,-1.8035,9,3,227.50,0.50475,4,1,True
8,DB00334,CN1CCN(CC1)C1=NC2=CC=CC=C2NC2=C1C=C(C)S2,Cc1cc2c(s1)=Nc1ccccc1NC=2N1CCN(C)CC1,FDA,Olanzapine,CC1=CC2=C(S1)NC3=CC=CC=C3N=C2N4CCN(CC4)C,312.440,3.0388,4,1,236.55,0.21319,0,1,True
9,DB00338,COC1=CC2=C(C=C1)N=C(N2)S(=O)CC1=NC=C(C)C(OC)=C1C,COc1ccc2[nH]c([S+]([O-])Cc3ncc(C)c(OC)c3C)nc2c1,FDA,Omeprazole,CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC,345.422,2.0920,6,1,260.23,0.30223,5,1,True
10,DB00384,NC1=NC(N)=C2N=C(C(N)=NC2=N1)C1=CC=CC=C1,N=c1[nH]c(=N)c2nc(-c3ccccc3)c(=N)[nH]c2[nH]1,FDA,Triamterene,C1=CC=C(C=C1)C2=NC3=C(N=C(N=C3N=C2N)N)N,253.268,0.6075,7,3,188.22,0.47652,1,1,True
11,DB00443,[H][C@@]12C[C@H](C)[C@](O)(C(=O)CO)[C@@]1(C)C[...,CC1CC2C3CC=C4CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,FDA,Dexamethasone,CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)CO)O...,392.465,1.2884,5,3,268.83,0.24320,2,1,True
12,DB00456,[H][C@@]1(NC(=O)CC2=CC=CS2)C(=O)N2C(C(O)=O)=C(...,CC(=O)OC=C1CSC2C(NC(=O)Cc3cccs3)C(=O)N2C1C(=O)O,FDA,Cephalothin,CC(=O)OCC1=C(N2C(C(C2=O)NC(=O)CC3=CC=CS3)SC1)C...,396.443,0.5912,8,2,270.26,0.47406,7,1,True
13,DB00507,CC(=O)OC1=CC=CC=C1C(=O)NC1=NC=C(S1)[N+]([O-])=O,CC(=O)Oc1ccccc1C(=O)N=c1[nH]cc([N+](=O)[O-])s1,FDA,nitazoxanide,CC(=O)OC1=CC=CC=C1C(=O)NC2=NC=C(S2)[N+](=O)[O-],307.285,1.6871,8,1,220.61,0.49540,5,1,True
14,DB00641,[H][C@]12[C@H](C[C@@H](C)C=C1C=C[C@H](C)[C@@H]...,CCC(C)(C)C(=O)OC1CC(C)C=C2C=CC(C)C(CCC3CC(O)CC...,FDA,Simvastatin,CCC(C)(C)C(=O)OC1CC(C=C2C1C(C(C=C2)C)CCC3CC(CC...,418.572,4.4608,5,1,327.83,0.18052,7,1,True
15,DB00760,[H][C@]1([C@@H](C)O)C(=O)N2C(C(O)=O)=C(S[C@@H]...,CC(O)C1C(=O)N2C(C(=O)O)=C(SC3CNC(C(=O)N(C)C)C3...,FDA,Meropenem,CC1C2C(C(=O)N2C(=C1SC3CC(NC3)C(=O)N(C)C)C(=O)O...,383.468,-3.1042,8,3,262.98,0.38547,5,1,True
16,DB00795,OC(=O)C1=CC(=CC=C1O)\N=N\C1=CC=C(C=C1)S(=O)(=O...,O=C(O)c1cc(N=Nc2ccc(S(=O)(=O)N=c3cccc[nH]3)cc2...,FDA,Sulfasalazine,C1=CC=NC(=C1)NS(=O)(=O)C2=CC=C(C=C2)N=NC3=CC(=...,398.398,2.6508,9,3,285.05,0.39737,5,1,True
17,DB00814,CN1C(C(=O)NC2=NC=C(C)S2)=C(O)C2=C(C=CC=C2)S1(=...,Cc1c[nH]c(=NC(=O)C2C(=O)c3ccccc3S(=O)(=O)N2C)s1,FDA,Meloxicam,CC1=CN=C(S1)NC(=O)C2=C(C3=CC=CC=C3S(=O)(=O)N2C)O,351.406,1.9072,7,2,236.10,0.42804,2,1,True
18,DB00860,[H][C@@]12CC[C@](O)(C(=O)CO)[C@@]1(C)C[C@H](O)...,CC12C=CC(=O)C=C1CCC1C2C(O)CC2(C)C1CCC2(O)C(=O)CO,FDA,Prednisolone,CC12CC(C3C(C1CCC2(C(=O)CO)O)CCC4=CC(=O)C=CC34C)O,360.448,1.1414,5,3,253.57,0.25784,2,1,True
19,DB00959,[H][C@@]12CC[C@](O)(C(=O)CO)[C@@]1(C)C[C@H](O)...,CC1=C2CC(=O)C=CC2(C)C2C(O)CC3(C)C(CCC3(O)C(=O)...,FDA,Methylprednisolone,CC1CC2C3CCC(C3(CC(C2C4(C1=CC(=O)C=C4)C)O)C)(C(...,374.475,1.4107,5,3,264.57,0.24712,2,1,True
20,DB01016,COC1=C(C=C(Cl)C=C1)C(=O)NCCC1=CC=C(C=C1)S(=O)(...,COc1ccc(Cl)cc1C(=O)NCCc1ccc(S(=O)(=O)NC(=O)NC2...,FDA,Glyburide,COC1=C(C=C(C=C1)Cl)C(=O)NCCC2=CC=C(C=C2)S(=O)(...,494.010,3.9494,8,3,364.48,0.27173,7,1,True
21,DB01017,[H][C@@]12CC3=C(C(O)=CC=C3N(C)C)C(=O)C1=C(O)[C...,CN(C)c1ccc(O)c2c1CC1CC3C(N(C)C)C(=O)C(C(N)=O)C...,FDA,Minocycline,CN(C)C1C2CC3CC4=C(C=CC(=C4C(=C3C(=O)C2(C(=C(C1...,457.481,-1.0304,10,5,310.84,0.36639,3,1,True
22,DB01024,COC1=C(C\C=C(/C)CCC(O)=O)C(O)=C2C(=O)OCC2=C1C,COc1c(CC=C(C)CCC(=O)O)c(O)c2c(O)occ2c1C,FDA,Mycophenolic Acid,CC1=C2COC(=O)C2=C(C(=C1OC)CC=C(C)CCC(=O)O)O,320.340,2.2970,6,2,244.49,0.29564,6,1,True
23,DB01030,CC[C@@]1(O)C(=O)OCC2=C1C=C1N(CC3=CC4=C(C=CC(O)...,CCC1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3c(CN(C)C)c(O...,FDA,Topotecan,CCC1(C2=C(COC1=O)C(=O)N3CC4=CC5=C(C=CC(=C5CN(C...,421.452,0.4610,8,2,294.78,0.27258,3,1,True
24,DB01128,CC(O)(CS(=O)(=O)C1=CC=C(F)C=C1)C(=O)NC1=CC(=C(...,CC(O)(CS(=O)(=O)c1ccc(F)cc1)C(=O)Nc1ccc(C#N)c(...,FDA,bicalutamide,CC(CS(=O)(=O)C1=CC=C(C=C1)F)(C(=O)NC2=CC(=C(C=...,430.377,2.1426,6,2,291.11,0.27392,6,1,True
25,DB01140,[H][C@]12SCC(C)=C(N1C(=O)[C@H]2NC(=O)[C@H](N)C...,CC1=C(C(=O)O)N2C(=O)C(NC(=O)C(N)c3ccc(O)cc3)C2SC1,FDA,Cefadroxil,CC1=C(N2C(C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)SC1)...,363.393,-2.3737,8,4,246.42,0.45893,4,1,True
26,DB01147,[H][C@]12SC(C)(C)[C@@H](N1C(=O)[C@H]2NC(=O)C1=...,Cc1onc(-c2ccccc2Cl)c1C(=O)NC1C(=O)N2C1SC(C)(C)...,FDA,Cloxacillin,CC1=C(C(=NO1)C2=CC=CC=C2Cl)C(=O)NC3C4N(C3=O)C(...,435.887,2.7038,8,2,293.43,0.37419,4,1,True
27,DB01254,CC1=NC(NC2=NC=C(S2)C(=O)NC2=C(C)C=CC=C2Cl)=CC(...,Cc1nc(=Nc2ncc(C(=O)Nc3c(C)cccc3Cl)s2)cc(N2CCN(...,FDA,Dasatinib,CC1=C(C(=CC=C1)Cl)NC(=O)C2=CN=C(S2)NC3=CC(=NC(...,488.014,3.6259,9,3,361.62,0.30261,7,1,True
28,DB01394,COC1=CC2=C(C(OC)=C1OC)C1=CC=C(OC)C(=O)C=C1[C@H...,COc1cc2c(c(OC)c1OC)-c1ccc(OC)c(=O)cc1C(NC(C)=O...,FDA,Colchicine,CC(=O)NC1CCC2=CC(=C(C(=C2C3=CC=C(C(=O)C=C13)OC...,399.442,1.8630,7,1,308.67,0.25121,5,1,True
29,DB06155,CC1=C(N(N=C1C(=O)NN1CCCCC1)C1=C(Cl)C=C(Cl)C=C1...,Cc1c(C(=O)NN2CCCCC2)nn(-c2ccc(Cl)cc2Cl)c1-c1cc...,FDA,Rimonabant,CC1=C(N(N=C1C(=O)NN2CCCCC2)C3=C(C=C(C=C3)Cl)Cl...,463.795,4.2064,5,1,334.07,0.13737,4,1,True
30,DB06268,CC1=NOC(NS(=O)(=O)C2=C(SC=C2)C(=O)CC2=CC3=C(OC...,Cc1cc2c(cc1CC(=O)c1sccc1S(=O)(=O)N=c1o[nH]c(C)...,FDA,sitaxsentan,CC1=CC2=C(C=C1CC(=O)C3=C(C=CS3)S(=O)(=O)NC4=C(...,454.910,3.3593,8,1,308.92,0.38366,5,1,True
31,DB06589,CN(C1=CC2=NN(C)C(C)=C2C=C1)C1=CC=NC(NC2=CC=C(C...,Cc1ccc(N=c2nc(N(C)c3ccc4c(C)n(C)nc4c3)cc[nH]2)...,FDA,pazopanib,CC1=C(C=C(C=C1)NC2=NC=CC(=N2)N(C)C3=CC4=NN(C(=...,437.527,1.7881,9,2,320.76,0.30752,5,1,True
32,DB06626,CNC(=O)C1=C(SC2=CC=C3C(NN=C3\C=C\C3=CC=CC=N3)=...,CNC(=O)c1ccccc1Sc1ccc2c(C=Cc3ccccn3)[nH]nc2c1,FDA,Axitinib,CNC(=O)C1=CC=CC=C1SC2=CC3=C(C=C2)C(=NN3)C=CC4=...,386.478,3.4441,5,2,299.93,0.25979,5,1,True
33,DB06725,CN1C(C(=O)NC2=CC=CC=N2)=C(O)C2=C(C=C(Cl)S2)S1(...,CN1C(C(=O)N=c2cccc[nH]2)C(=O)c2sc(Cl)cc2S1(=O)=O,FDA,lornoxicam,CN1C(=C(C2=C(S1(=O)=O)C=C(S2)Cl)O)C(=O)NC3=CC=...,371.824,1.8836,7,2,239.26,0.42239,2,1,True
34,DB08865,[H][C@](C)(OC1=CC(=CN=C1N)C1=CN(N=C1)C1CCNCC1)...,CC(Oc1cc(-c2cnn(C3CCNCC3)c2)c[nH]c1=N)c1c(Cl)c...,FDA,Crizotinib,CC(C1=C(C=CC(=C1Cl)F)Cl)OC2=C(N=CC(=C2)C3=CN(N...,450.344,3.5382,6,2,325.47,0.20137,5,1,True
35,DB08877,N#CC[C@H](C1CCCC1)N1C=C(C=N1)C1=C2C=CNC2=NC=N1,N#CCC(C1CCCC1)n1cc(-c2ncnc3[nH]ccc23)cn1,FDA,ruxolitinib,C1CCC(C1)C(CC#N)N2C=C(C=N2)C3=C4C=CNC4=NC=N3,306.372,1.6767,6,1,244.68,0.27518,4,1,True
36,DB08881,CCCS(=O)(=O)NC1=C(F)C(C(=O)C2=CNC3=NC=C(C=C23)...,CCCS(=O)(=O)Nc1ccc(F)c(C(=O)c2c[nH]c3ncc(-c4cc...,FDA,Vemurafenib,CCCS(=O)(=O)NC1=C(C(=C(C=C1)F)C(=O)C2=CNC3=C2C...,489.929,4.5779,6,2,341.40,0.22859,6,1,True
37,DB08895,C[C@@H]1CCN(C[C@@H]1N(C)C1=NC=NC2=C1C=CN2)C(=O...,CC1CCN(C(=O)CC#N)CC1N(C)c1ncnc2[nH]ccc12,FDA,tofacitinib,CC1CCN(CC1N(C)C2=NC=NC3=C2C=CN3)C(=O)CC#N,312.376,1.1936,7,1,246.07,0.28297,3,1,True
38,DB08899,CNC(=O)C1=C(F)C=C(C=C1)N1C(=S)N(C(=O)C1(C)C)C1...,CNC(=O)c1ccc(N2C(=S)N(c3ccc(C#N)c(C(F)(F)F)c3)...,FDA,enzalutamide,CC1(C(=O)N(C(=S)N1C2=CC(=C(C=C2)C(=O)NC)F)C3=C...,464.442,3.5872,6,1,324.50,0.26564,4,1,True
39,DB08910,NC1=CC=CC2=C1C(=O)N(C1CCC(=O)NC1=O)C2=O,Nc1cccc2c1C(=O)N(C1CCC(=O)NC1=O)C2=O,FDA,pomalidomide,C1CC(=O)NC(=O)C1N2C(=O)C3=C(C2=O)C(=CC=C3)N,273.247,-0.5679,7,2,187.56,0.43954,1,1,True
40,DB09053,NC1=NC=NC2=C1C(=NN2[C@@H]1CCCN(C1)C(=O)C=C)C1=...,C=CC(=O)N1CCCC(n2nc(-c3ccc(Oc4ccccc4)cc3)c3c(=...,FDA,ibrutinib,C=CC(=O)N1CCCC(C1)N2C3=NC=NC(=C3C(=N2)C4=CC=C(...,440.506,3.6932,8,1,338.01,0.24153,5,1,True
41,DB09054,[H][C@@](CC)(NC1=NC=NC2=C1N=CN2)C1=NC2=CC=CC(F...,CCC(N=c1[nH]cnc2[nH]cnc12)c1nc2cccc(F)c2c(=O)n...,FDA,idelalisib,CCC(C1=NC2=C(C(=CC=C2)F)C(=O)N1C3=CC=CC=C3)NC4...,415.431,2.8580,8,2,307.08,0.28156,5,1,True
42,DB09073,CC(=O)C1=C(C)C2=CN=C(NC3=NC=C(C=C3)N3CCNCC3)N=...,CC(=O)c1c(C)c2c[nH]c(=Nc3ccc(N4CCNCC4)cn3)nc2n...,FDA,palbociclib,CC1=C(C(=O)N(C2=NC(=NC=C12)NC3=NC=C(C=C3)N4CCN...,447.541,2.0030,9,2,337.84,0.26347,5,1,True
43,DB09074,FC1=CC=C(CC2=NNC(=O)C3=CC=CC=C23)C=C1C(=O)N1CC...,O=C(c1cc(Cc2n[nH]c(=O)c3ccccc23)ccc1F)N1CCN(C(...,FDA,olaparib,C1CC1C(=O)N2CCN(CC2)C(=O)C3=C(C=CC(=C3)CC4=NNC...,434.470,3.1669,7,1,315.97,0.21898,4,1,True
44,DB11656,OC(=O)C(CC1=CC(=O)NC2=C1C=CC=C2)NC(=O)C1=CC=C(...,O=C(NC(Cc1cc(=O)[nH]c2ccccc12)C(=O)O)c1ccc(Cl)cc1,FDA,rebamipide,C1=CC=C2C(=C1)C(=CC(=O)N2)CC(C(=O)O)NC(=O)C3=C...,370.791,1.6962,6,3,268.43,0.27992,5,1,True
45,DB11703,CC#CC(=O)N1CCC[C@H]1C1=NC(=C2N1C=CN=C2N)C1=CC=...,CC#CC(=O)N1CCCC1c1nc(-c2ccc(C(=O)N=c3cccc[nH]3...,FDA,acalabrutinib,CC#CC(=O)N1CCCC1C2=NC(=C3N2C=CN=C3N)C4=CC=C(C=...,465.516,2.6784,9,2,362.43,0.26824,4,1,True
46,DB11760,CN1N=CN=C1[C@@H]1[C@H](NC2=C3C1=NNC(=O)C3=CC(F...,CN1NCNC1=c1c(-c2ccc(F)cc2)nc2cc(F)cc3c(=O)[nH]...,FDA,talazoparib,CN1C(=NC=N1)C2C(NC3=CC(=CC4=C3C2=NNC4=O)F)C5=C...,380.357,2.0485,7,2,266.10,0.28666,2,1,True
47,DB11942,FC(F)(F)C1=CC(=CC(=C1)C1=NN(\C=C/C(=O)NNC2=NC=...,O=C(C=Cn1cnc(-c2cc(C(F)(F)F)cc(C(F)(F)F)c2)n1)...,FDA,selinexor,C1=CN=C(C=N1)NNC(=O)C=CN2C=NC(=N2)C3=CC(=CC(=C...,443.310,2.5720,8,2,303.11,0.28607,7,1,True
48,DB14086,O[C@H]1CC2=C(O)C=C(O)C=C2O[C@@H]1C1=CC=C(O)C(O...,Oc1cc(O)c2c(c1)OC(c1ccc(O)c(O)c1)C(O)C2,FDA,Catechin,C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)O,290.270,1.5087,6,5,200.03,0.37744,1,1,True

In [ ]:
# Guardar los resultados en un archivo CSV
resultados.to_csv('resultados_Lead_FDA.csv', index=False)